### ISSUE TITLE
__init__.py file has incorrect character encoding

### ISSUE THREAD

**Issue by GWARDAR** [svenh0/GithubPluginUpdater#1]
Hello! __init__.py file has incorrect character encoding (please check)
And if you can add the ability to translate the plugin into different languages.

**Comment by svenh0** [comment]
Thanks for feedback.
I will fix the encoding of init-file and add multi-language support in the next update.

**Comment by GWARDAR** [comment]
Thanks a lot!!!!
My poedit noticed this :) and refused to seize lines for translation. With the wrong encoding, the string looks like this
interval_options.append (("1", "stьndlich"))
Thanks again !!!

**Comment by svenh0** [comment]
update is online

**Comment by GWARDAR** [comment]
Dear Author, Thank you very much for your work! (no problem) Everything is very Good!
